name: qmdb
description: "Flutter assignment for Q Agency"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  alice: ^0.4.2
  dio: ^5.6.0
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  fpdart: ^1.1.0
  connectivity_plus: ^6.0.5
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  path_provider: ^2.1.4
  retrofit: ^4.4.1
  logger: 2.0.2+1
  easy_infinite_pagination: ^0.0.6
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.2.1

  build_runner: ^2.4.6
  retrofit_generator: '>=8.0.0 <10.0.0'
  json_serializable: ^6.7.0
  json_annotation: ^4.9.0
  freezed_annotation: 2.2.0
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/